{{- if and .Values.tls.enabled .Values.tls.certs.certManager.enabled }}
{{- if .Values.tls.certs.useCertManagerV1CRDs }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cert-manager.io/v1alpha2
{{- end }}
kind: Certificate
metadata:
  name: {{ template "cockroachdb.fullname" . }}-node
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 521
  commonName: node
  subject:
    {{- with .Values.tls.certs.certManagerIssuer.organizations }}
    organizations: {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.tls.ipAddresses }}
  ipAddresses: {{- toYaml . | nindent 4 }}
  {{- end }}
  dnsNames:
    - "localhost"
    {{- range $i, $_ := until (.Values.statefulset.replicas | int) }}
    - "{{ template "cockroachdb.fullname" $ }}-{{ $i }}.{{ $.Values.clusterInfo.fqdn }}"
    {{- end }}
    - {{ printf "%s-internal" (include "cockroachdb.fullname" .) | quote }}
    - {{ printf "%s-internal.%s" (include "cockroachdb.fullname" .) .Release.Namespace | quote }}
    - {{ printf "%s-internal.%s.svc" (include "cockroachdb.fullname" .) .Release.Namespace | quote }}
    - {{ printf "%s-internal.%s.svc.%s" (include "cockroachdb.fullname" .) .Release.Namespace .Values.clusterDomain | quote }}
    - {{ printf "%s-public" (include "cockroachdb.fullname" .) | quote }}
    - {{ printf "%s-public.%s" (include "cockroachdb.fullname" .) .Release.Namespace | quote }}
    - {{ printf "%s-public.%s.svc" (include "cockroachdb.fullname" .) .Release.Namespace | quote }}
    - {{ printf "%s-public.%s.svc.%s" (include "cockroachdb.fullname" .) .Release.Namespace .Values.clusterDomain | quote }}
{{- with .Values.tls.certs.certManager.dnsNames -}}
{{ toYaml . | nindent 4 }}
{{- end}}
  secretName: {{ template "cockroachdb.fullname" . }}-node
  issuerRef:
    name: {{ .Values.tls.certs.certManagerIssuer.name }}
    kind: {{ .Values.tls.certs.certManagerIssuer.kind }}
    group: {{ .Values.tls.certs.certManagerIssuer.group }}
{{- end }}
