---
apiVersion: v2
name: cockroachdb
version: 2.4.0
appVersion: v23.1.8
description: Multi-k8s cockroach deployment
sources:
  - https://github.com/cockroachdb/cockroach
dependencies:
  - name: reloader
    version: "1.0.107"
    condition: reloader.enabled
    repository: "https://stakater.github.io/stakater-charts"
  - name: common
    version: 2.27.0
    repository: https://charts.bitnami.com/bitnami
