---
apiVersion: v2
name: cockroachdb
version: 2.3.1
appVersion: v22.1.11
description: Multi-k8s cockroach deployment
sources:
  - https://github.com/cockroachdb/cockroach
dependencies:
  - name: reloader
    version: "v0.0.129"
    condition: reloader.enabled
    repository: "https://stakater.github.io/stakater-charts"
  - name: common
    version: 2.2.4
    repository: https://charts.bitnami.com/bitnami
